name: Ansible Vault

on:
  workflow_call:
    inputs:
      password_01:
        required: true
        type: string
      password_02:
        required: false
        type: string
      password_03:
        required: false
        type: string
      password_04:
        required: false
        type: string
      password_05:
        required: false
        type: string
      password_06:
        required: false
        type: string
      password_07:
        required: false
        type: string
      password_08:
        required: false
        type: string
      password_09:
        required: false
        type: string
      password_10:
        required: false
        type: string
    secrets:
      PRIVATECIRCLE_CI_GITHUB_USER_PAT:
        required: true
      USER_ANSIBLE_VAULT_PASSWORD:
        required: true

jobs:
  ansible-vault:
    name: "Ansible vault encryption"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ansible vault encrypted secrets
        run: |
          echo "Running ansible vault encryption..."
          echo "$USER_ANSIBLE_VAULT_PASSWORD" > user_vault_password.txt
          sudo chmod 600 user_vault_password.txt
          for i in {01..10};do
          if [ $(jq -r ".inputs.password_$i" "$GITHUB_EVENT_PATH") != null ]; then
          PASSWORD=$(jq -r ".inputs.password_$i" "$GITHUB_EVENT_PATH")
          echo "Ansible-vault encrypted secret for PASSWORD_$i"
          ansible-vault encrypt_string "$PASSWORD" --vault-id user@user_vault_password.txt
          echo
          fi
          done
          rm user_vault_password.txt
        env:
          USER_ANSIBLE_VAULT_PASSWORD: ${{ secrets.USER_ANSIBLE_VAULT_PASSWORD }}
