name: Ansible Vault

on:
  workflow_call:
    secrets:
      PRIVATECIRCLE_CI_GITHUB_USER_PAT:
        required: true
      USER_ANSIBLE_VAULT_PASSWORD:
        required: true
      PASSWORD_01:
        required: true
      PASSWORD_02:
        required: false
      PASSWORD_03:
        required: false
      PASSWORD_04:
        required: false
      PASSWORD_05:
        required: false
      PASSWORD_06:
        required: false
      PASSWORD_07:
        required: false
      PASSWORD_08:
        required: false
      PASSWORD_09:
        required: false
      PASSWORD_10:
        required: false

jobs:
  ansible-vault:
    name: Ansible Vault
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout Ansible Repo
        uses: actions/checkout@v2
        with:
          repository: private-circle/infra-ansible
          ref: main
          token: ${{ secrets.PRIVATECIRCLE_CI_GITHUB_USER_PAT }}
          path: ./infra-ansible

      - name: Run Ansible vault encryption
        id: ansible-run
        uses: ./infra-ansible/.github/actions/ansible-vault
        with:
          user_ansible_vault_password: ${{ secrets.USER_ANSIBLE_VAULT_PASSWORD }}
          password_01: ${{ secrets.PASSWORD_01 }}
          password_02: ${{ secrets.PASSWORD_02 }}
          password_03: ${{ secrets.PASSWORD_03 }}
          password_04: ${{ secrets.PASSWORD_04 }}
          password_05: ${{ secrets.PASSWORD_05 }}
          password_06: ${{ secrets.PASSWORD_06 }}
          password_07: ${{ secrets.PASSWORD_07 }}
          password_08: ${{ secrets.PASSWORD_08 }}
          password_09: ${{ secrets.PASSWORD_09 }}
          password_10: ${{ secrets.PASSWORD_10 }}
