name: TI - Destroy or Delete

on:
  workflow_call:
    inputs:
      stack_id:
        description: 'Identifier for which stack to be deployed (eg pc-linode-infra-parth-mongodb2-xxxxxx)'
        required: true
      cmd:
        description: 'Whether to destory or delete this stack. Must be destroyed before calling delete'
        default: "DESTROY"
        required: true
    secrets:
      PRIVATECIRCLE_CI_GITHUB_USER_PAT :
        required: true

jobs:
  destroy:
    name: "DESTROY Stack"
    if: ${{ github.event.inputs.cmd == 'DESTROY' }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set deployPath variable
        id: vars
        run: echo "::set-output name=deployPath::./terraform/live/ti"

      - name: Copy sample delete folder
        working-directory: ./terraform/live/ti
        run: |
          source_dir="$GITHUB_WORKSPACE/terraform/samples/destroy";
          if ! test -d "$source_dir"; then
            echo "$source_dir not found!";
            exit 1
          fi

          rm -rf ${{ github.event.inputs.stack_id }}
          cp -R ../../samples/destroy ${{ github.event.inputs.stack_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PRIVATECIRCLE_CI_GITHUB_USER_PAT }}
          author: privatecircle-ci <privatecircle-ci@users.noreply.github.com>
          title: "Destroyed Stack - ${{ github.event.inputs.stack_id }}"
          branch: "destroy-${{ github.event.inputs.stack_id }}"
          commit-message: "Destroyed Stack - ${{ github.event.inputs.stack_id }}"
          body: |
            **Github Action has created this PR to automatically destroy transient infra folder `${{ github.event.inputs.stack_id }}`**

            - Placed empty `main.tf` file into folder `${{ github.event.inputs.stack_id }}`

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request

  delete:
    name: "DELETE Stack"
    if: ${{ github.event.inputs.cmd == 'DELETE' }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check if destroyed, else fail.
        working-directory: ./terraform/live/ti
        run: |
          #!/bin/bash
          set -x

          DIFF=$(diff ${{ github.event.inputs.stack_id}} ../../samples/destroy)
          if [ "$DIFF" != "" ]
          then
              echo "Running DELETE on a live stack. Please run DESTROY first."
              exit 2
          fi

      - name: Remove stack folder
        run: |
          rm -rf "$GITHUB_WORKSPACE/terraform/live/ti/${{ github.event.inputs.stack_id }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PRIVATECIRCLE_CI_GITHUB_USER_PAT }}
          author: privatecircle-ci <privatecircle-ci@users.noreply.github.com>
          title: "Deleted Stack - ${{ github.event.inputs.stack_id }}"
          branch: "delete-${{ github.event.inputs.stack_id }}"
          commit-message: "Deleted Stack - ${{ github.event.inputs.stack_id }}"
          body: |
            **Github Action has created this PR to automatically delete transient infra folder `${{ github.event.inputs.stack_id }}`**

            - Removed folder `${{ github.event.inputs.stack_id }}`

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
