name: TI - Mongodb Standalone & Replicaset

on:
  workflow_call:
    inputs:
      id:
        description: "Identifier for this deployment (eg parth-mongodb2)"
        required: true
      vm_region:
        description: "VM region ( eg  ap-west )"
        required: true
        default: "ap-west"
      vm_count:
        description: "VM count ( eg  2 )"
        required: true
        default: "1"
      vm_type:
        description: "vm type (eg g6-nanode-1 )"
        required: true
        default: "g6-nanode-1"
      vm_image:
        description: "VM image (eg linode/ubuntu18.04)"
        required: true
        default: "linode/ubuntu18.04"
      vm_tags:
        description: "VM tags (eg terraform-ti,infra)"
        required: true
        default: "terraform-ti"
      vm_authorized_users:
        description: "Authorized user emails (eg user1@privatecircle.co,user2@privatecircle.co)"
        required: true
    secrets:
      PRIVATECIRCLE_CI_GITHUB_USER_PAT :
        required: true

jobs:
  create-pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIVATECIRCLE_CI_GITHUB_USER_PAT }}

      - name: Set deployId variable
        id: vars
        run: |
          if ${{ github.event.inputs.vm_count == '1' }}; then
          echo "::set-output name=deployID::mongodb-standalone-${{ github.event.inputs.id }}-$(openssl rand -hex 32 | cut -c-3)"
          else
          echo "::set-output name=deployID::mongodb-replicaset-${{ github.event.inputs.id }}-$(openssl rand -hex 32 | cut -c-3)"
          fi

      - name: Create commits
        run: |
          dest_dir=${{ steps.vars.outputs.deployID }};
          (
            cd terraform || exit 1;
            cp -rv ../samples/mongodb-standalone-replicaset ti/$dest_dir;
            terragrunt_template=../samples/terragrunt.hcl.subdir;
            dest_file="$dest_dir/terragrunt.hcl"
            test -f "$terragrunt_template" && cp -v "$terragrunt_template" "$dest_file"
            sed -i 's+LINODE_REGION+${{github.event.inputs.vm_region}}+g' $dest_dir/.auto.tfvars.json
            sed -i 's+LINODE_IMAGE+${{github.event.inputs.vm_image}}+g' $dest_dir/.auto.tfvars.json
            sed -i 's+LINODE_TYPE+${{github.event.inputs.vm_type}}+g' $dest_dir/.auto.tfvars.json
            sed -i 's+LINODE_LABEL+${{github.event.inputs.id}}+g' $dest_dir/.auto.tfvars.json
            sed -i 's+LINODE_TAGS+${{github.event.inputs.vm_tags}}+g' $dest_dir/.auto.tfvars.json
            sed -i 's+LINODE_COUNT+${{github.event.inputs.vm_count}}+g' $dest_dir/.auto.tfvars.json
            sed -i 's+AUTHORIZED_USERS+${{github.event.inputs.vm_authorized_users}}+g' $dest_dir/.auto.tfvars.json
            sed -i 's+REPLICASET_NAME+${{github.event.inputs.id}}+g' $dest_dir/inventory.tmpl
          )

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PRIVATECIRCLE_CI_GITHUB_USER_PAT }}
          author: privatecircle-ci <privatecircle-ci@users.noreply.github.com>
          title: Setup TI - ${{ steps.vars.outputs.deployID }}
          branch: ${{ steps.vars.outputs.deployID }}
          commit-message: Setup TI - ${{ steps.vars.outputs.deployID }}
          body: |
            **Github Action has created this PR to automatically create a transient infra for `${{ steps.vars.outputs.deployID }}`**
            - Contains a Terraform plan to setup `${{ steps.vars.outputs.deployID }}`
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
