name: TI - Mongodb Sharded Cluster

on:
  workflow_call:
    inputs:
      id:
        description: "Identifier for this deployment (eg parth-mongodb2)"
        required: true
      config_vm_count:
        description: "Config vm count ( eg  2 )"
        required: true
        default: "1"
      config_vm_type:
        description: "Config vm type (eg g6-nanode-1 )"
        required: true
        default: "g6-nanode-1"
      mongos_vm_count:
        description: "Mongos vm count ( eg  2 )"
        required: true
        default: "1"
      mongos_vm_type:
        description: "Mongos vm type (eg g6-nanode-1 )"
        required: true
        default: "g6-nanode-1"
      shard_count:
        description: "No. of shards ( eg  2 )"
        required: true
        default: "1"
      shard_vm_type:
        description: "Shard vm type (eg g6-nanode-1 )"
        required: true
        default: "g6-nanode-1"
      per_shard_vm_count:
        description: "VM count in each shard ( eg  2 )"
        required: true
        default: "1"
      vm_tags:
        description: "VM tags (eg terraform-ti,infra)"
        required: true
        default: "terraform-ti"
      vm_authorized_users:
        description: "Authorized user emails (eg user1@privatecircle.co,user2@privatecircle.co)"
        required: true
    secrets:
      PRIVATECIRCLE_CI_GITHUB_USER_PAT :
        required: true

jobs:
  create-pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIVATECIRCLE_CI_GITHUB_USER_PAT }}

      - name: Set deployId variable for sharded
        id: vars
        run: echo "::set-output name=deployID::mongodb-sharded-${{ github.event.inputs.id }}-$(openssl rand -hex 32 | cut -c-3)"

      - name: Create commits
        run: |
          dest_dir=${{ steps.vars.outputs.deployID }};
          (
            cd terraform/live || exit 1;
            mkdir -pv ti;
            cp -rv ../samples/mongodb-sharded-cluster ti/$dest_dir;
            terragrunt_template=../samples/terragrunt.hcl.subdir;
            dest_file="ti/$dest_dir/terragrunt.hcl"
            test -f "$terragrunt_template" && cp -v "$terragrunt_template" "$dest_file"
            sed -i 's+CONFIG_LINODE_COUNT+${{github.event.inputs.config_vm_count}}+g' ti/$dest_dir/.auto.tfvars.json
            sed -i 's+CONFIG_LINODE_TYPE+${{github.event.inputs.config_vm_type}}+g' ti/$dest_dir/.auto.tfvars.json
            sed -i 's+MONGOS_LINODE_COUNT+${{github.event.inputs.mongos_vm_count}}+g' ti/$dest_dir/.auto.tfvars.json
            sed -i 's+MONGOS_LINODE_TYPE+${{github.event.inputs.mongos_vm_type}}+g' ti/$dest_dir/.auto.tfvars.json
            sed -i 's+SHARD_COUNT+${{github.event.inputs.shard_count}}+g' ti/$dest_dir/.auto.tfvars.json
            sed -i 's+SHARD_LINODE_TYPE+${{github.event.inputs.shard_vm_type}}+g' ti/$dest_dir/.auto.tfvars.json
            sed -i 's+PER_SHARD_VM_COUNT+${{github.event.inputs.per_shard_vm_count}}+g' ti/$dest_dir/.auto.tfvars.json
            sed -i 's+LINODE_LABEL+${{github.event.inputs.id}}+g' ti/$dest_dir/.auto.tfvars.json
            sed -i 's+LINODE_TAGS+${{github.event.inputs.vm_tags}}+g' ti/$dest_dir/.auto.tfvars.json
            sed -i 's+AUTHORIZED_USERS+${{github.event.inputs.vm_authorized_users}}+g' ti/$dest_dir/.auto.tfvars.json
            sed -i 's+REPLICASET_NAME+${{github.event.inputs.id}}+g' ti/$dest_dir/inventory.tmpl
          )

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PRIVATECIRCLE_CI_GITHUB_USER_PAT }}
          author: privatecircle-ci <privatecircle-ci@users.noreply.github.com>
          title: Setup TI - ${{ steps.vars.outputs.deployID }}
          branch: ${{ steps.vars.outputs.deployID }}
          commit-message: Setup TI - ${{ steps.vars.outputs.deployID }}
          body: |
            **Github Action has created this PR to automatically create a transient infra for `${{ steps.vars.outputs.deployID }}`**
            - Contains a Terraform plan to setup `${{ steps.vars.outputs.deployID }}`
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
